/** Explicit application delegation contract. API services remain the permission authority. */
export const NEW_APPLICATION_SCOPES = [
  "account:connections:revoke",
  "account:read",
  "account:tokens:revoke",
  "admin:read",
  "admin:settings",
  "admin:tokens:revoke",
  "admin:users",
  "architectures:write",
  "libraries:bind",
  "organizations:read",
  "organizations:write",
  "sharing:read",
  "sharing:write",
  "skills:manage",
  "submissions:read",
  "targets:control",
  "targets:read",
  "teams:read",
  "teams:write"
] as const;

export const APPLICATION_SCOPES = [
  "profile:read",
  "skills:read",
  "architectures:read",
  "skills:submit",
  "review:read",
  "review:write",
  "improvements:read",
  "improvements:configure",
  "improvements:run",
  "improvements:report",
  "libraries:read",
  "libraries:write",
  "account:connections:revoke",
  "account:read",
  "account:tokens:revoke",
  "admin:read",
  "admin:settings",
  "admin:tokens:revoke",
  "admin:users",
  "architectures:write",
  "libraries:bind",
  "organizations:read",
  "organizations:write",
  "sharing:read",
  "sharing:write",
  "skills:manage",
  "submissions:read",
  "targets:control",
  "targets:read",
  "teams:read",
  "teams:write"
] as const;

export const APPLICATION_PRIVILEGED_SCOPES = [
  "admin:read",
  "admin:settings",
  "admin:tokens:revoke",
  "admin:users",
  "architectures:write",
  "improvements:configure",
  "improvements:report",
  "improvements:run",
  "libraries:bind",
  "libraries:write",
  "organizations:write",
  "review:read",
  "review:write",
  "sharing:read",
  "sharing:write",
  "skills:submit",
  "targets:control",
  "teams:write"
] as const;

export type ApplicationScope = (typeof APPLICATION_SCOPES)[number];

export interface DelegatedAction {
  readonly id: string;
  readonly capabilityId: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly route: string;
  readonly requiredScopes: readonly ApplicationScope[];
  readonly assurance: string;
  readonly classification: "delegated_action" | "public_metadata";
}

export const DELEGATED_ACTIONS = [
  {"id": "draft.list", "capabilityId": "PUB-10", "method": "GET", "route": "/v1/drafts", "requiredScopes": ["submissions:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "draft.get", "capabilityId": "PUB-10", "method": "GET", "route": "/v1/drafts/:id", "requiredScopes": ["submissions:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "draft.history", "capabilityId": "PUB-10", "method": "GET", "route": "/v1/drafts/:id/history", "requiredScopes": ["submissions:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "draft.revision", "capabilityId": "PUB-10", "method": "GET", "route": "/v1/drafts/:id/revisions/:revision", "requiredScopes": ["submissions:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "draft.create", "capabilityId": "PUB-10", "method": "POST", "route": "/v1/drafts", "requiredScopes": ["skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "draft.update", "capabilityId": "PUB-10", "method": "PUT", "route": "/v1/drafts/:id", "requiredScopes": ["skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "draft.preview", "capabilityId": "PUB-10", "method": "POST", "route": "/v1/drafts/preview", "requiredScopes": ["skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "draft.validate", "capabilityId": "PUB-10", "method": "POST", "route": "/v1/drafts/:id/validate", "requiredScopes": ["skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "draft.submit", "capabilityId": "PUB-10", "method": "POST", "route": "/v1/drafts/:id/submit", "requiredScopes": ["skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "architecture_artifacts.prepare", "capabilityId": "ARC-11", "method": "POST", "route": "/v1/architecture-targets/:id/artifacts", "requiredScopes": ["targets:control", "architectures:read", "skills:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "architecture_artifacts.get", "capabilityId": "ARC-11", "method": "GET", "route": "/v1/architecture-artifacts/:id", "requiredScopes": ["targets:read", "architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architecture_plans.create", "capabilityId": "ARC-10", "method": "POST", "route": "/v1/architecture-targets/:id/plans", "requiredScopes": ["targets:control", "architectures:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "architecture_plans.list", "capabilityId": "ARC-10", "method": "GET", "route": "/v1/architecture-targets/:id/plans", "requiredScopes": ["targets:read", "architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architecture_plans.get", "capabilityId": "ARC-10", "method": "GET", "route": "/v1/architecture-plans/:id", "requiredScopes": ["targets:read", "architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architecture_plans.approve", "capabilityId": "ARC-10", "method": "POST", "route": "/v1/architecture-plans/:id/approve", "requiredScopes": ["targets:control", "architectures:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "skills.discover", "capabilityId": "REG-11", "method": "POST", "route": "/v1/skills/discover", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},

  {"id": "skills.list", "capabilityId": "REG-01", "method": "GET", "route": "/v1/skills", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "skills.get", "capabilityId": "REG-02", "method": "GET", "route": "/v1/skills/:slug", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "skills.releases.list", "capabilityId": "REG-03", "method": "GET", "route": "/v1/skills/:slug/releases", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "skills.releases.get", "capabilityId": "REG-04", "method": "GET", "route": "/v1/skills/:slug/releases/:version", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "skills.releases.export", "capabilityId": "REG-05", "method": "GET", "route": "/v1/skills/:slug/releases/:version/bundle", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "skills.managed.list", "capabilityId": "REG-06", "method": "GET", "route": "/v1/manage/skills", "requiredScopes": ["skills:manage"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "skills.managed.get", "capabilityId": "REG-06", "method": "GET", "route": "/v1/manage/skills/:slug", "requiredScopes": ["skills:manage"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "account.github.get", "capabilityId": "GIT-01", "method": "GET", "route": "/v1/account/github", "requiredScopes": ["account:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "account.github.disconnect", "capabilityId": "GIT-01", "method": "DELETE", "route": "/v1/account/github", "requiredScopes": ["account:connections:revoke"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "admin.github.get", "capabilityId": "GIT-02", "method": "GET", "route": "/v1/admin/github", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.github.test", "capabilityId": "GIT-02", "method": "POST", "route": "/v1/admin/github/test", "requiredScopes": ["admin:settings"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "skills.metadata.update", "capabilityId": "REG-07", "method": "PUT", "route": "/v1/skills/:slug", "requiredScopes": ["review:write"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "skills.lifecycle.decide", "capabilityId": "REG-08", "method": "POST", "route": "/v1/skills/:slug/actions", "requiredScopes": ["review:write"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "skills.releases.lifecycle.decide", "capabilityId": "REG-09", "method": "POST", "route": "/v1/skills/:slug/releases/:version/actions", "requiredScopes": ["review:write"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "skills.sharing.get", "capabilityId": "REG-10", "method": "GET", "route": "/v1/skills/:slug/sharing", "requiredScopes": ["sharing:read"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "skills.sharing.replace", "capabilityId": "REG-10", "method": "PUT", "route": "/v1/skills/:slug/sharing", "requiredScopes": ["sharing:write"], "assurance": "mfa_if_privileged_role_or_team_organization_visibility_expansion", "classification": "delegated_action"},
  {"id": "registry.catalog.list", "capabilityId": "BUN-01", "method": "GET", "route": "/v1/registry/catalog", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "bundles.list", "capabilityId": "BUN-01", "method": "GET", "route": "/v1/bundles", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "bundles.get", "capabilityId": "BUN-01", "method": "GET", "route": "/v1/bundles/:id", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "bundles.members.list", "capabilityId": "BUN-01", "method": "GET", "route": "/v1/bundles/:id/members", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "skills.bundles.list", "capabilityId": "BUN-01", "method": "GET", "route": "/v1/skills/:slug/bundles", "requiredScopes": ["skills:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "bundles.sources.list", "capabilityId": "BUN-02", "method": "GET", "route": "/v1/bundle-sources", "requiredScopes": ["skills:read", "libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "bundles.create", "capabilityId": "BUN-03", "method": "POST", "route": "/v1/bundles", "requiredScopes": ["skills:read", "skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "bundles.update", "capabilityId": "BUN-03", "method": "PATCH", "route": "/v1/bundles/:id", "requiredScopes": ["skills:read", "skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "bundles.library_reference.create", "capabilityId": "BUN-04", "method": "POST", "route": "/v1/bundles/:id/library-references", "requiredScopes": ["skills:read", "libraries:write"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "submissions.create", "capabilityId": "PUB-01", "method": "POST", "route": "/v1/submissions", "requiredScopes": ["skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "submissions.mine.list", "capabilityId": "PUB-02", "method": "GET", "route": "/v1/submissions/mine", "requiredScopes": ["submissions:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "submissions.mine.get", "capabilityId": "PUB-03", "method": "GET", "route": "/v1/submissions/:id", "requiredScopes": ["submissions:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "submissions.mine.export", "capabilityId": "PUB-04", "method": "GET", "route": "/v1/submissions/:id/bundle", "requiredScopes": ["submissions:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "submissions.mine.withdraw", "capabilityId": "PUB-05", "method": "POST", "route": "/v1/submissions/:id/actions", "requiredScopes": ["skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "review.submissions.list", "capabilityId": "PUB-06", "method": "GET", "route": "/v1/review/submissions", "requiredScopes": ["review:read"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "review.submissions.get", "capabilityId": "PUB-07", "method": "GET", "route": "/v1/review/submissions/:id", "requiredScopes": ["review:read"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "review.submissions.export", "capabilityId": "PUB-08", "method": "GET", "route": "/v1/review/submissions/:id/bundle", "requiredScopes": ["review:read"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "review.submissions.decide", "capabilityId": "PUB-09", "method": "POST", "route": "/v1/review/submissions/:id/actions", "requiredScopes": ["review:write"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "libraries.list", "capabilityId": "LIB-01", "method": "GET", "route": "/v1/libraries", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "libraries.get", "capabilityId": "LIB-01", "method": "GET", "route": "/v1/libraries/:libraryId", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "libraries.create", "capabilityId": "LIB-02", "method": "POST", "route": "/v1/libraries", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "libraries.update", "capabilityId": "LIB-03", "method": "PATCH", "route": "/v1/libraries/:libraryId", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "libraries.delete", "capabilityId": "LIB-04", "method": "DELETE", "route": "/v1/libraries/:libraryId", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "libraries.entries.list", "capabilityId": "LIB-05", "method": "GET", "route": "/v1/libraries/:libraryId/entries", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "libraries.collections.list", "capabilityId": "LIB-26", "method": "GET", "route": "/v1/libraries/:libraryId/collections", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_collections.get", "capabilityId": "LIB-26", "method": "GET", "route": "/v1/library-collections/:collectionId", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_collections.members.list", "capabilityId": "LIB-26", "method": "GET", "route": "/v1/library-collections/:collectionId/members", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "libraries.collections.create", "capabilityId": "LIB-27", "method": "POST", "route": "/v1/libraries/:libraryId/collections", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "library_collections.update", "capabilityId": "LIB-27", "method": "PATCH", "route": "/v1/library-collections/:collectionId", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "library_collections.delete", "capabilityId": "LIB-27", "method": "DELETE", "route": "/v1/library-collections/:collectionId", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "libraries.groups.list", "capabilityId": "LIB-28", "method": "GET", "route": "/v1/libraries/:libraryId/groups", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_groups.get", "capabilityId": "LIB-28", "method": "GET", "route": "/v1/library-groups/:groupId", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_groups.members.list", "capabilityId": "LIB-28", "method": "GET", "route": "/v1/library-groups/:groupId/members", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "libraries.groups.create", "capabilityId": "LIB-29", "method": "POST", "route": "/v1/libraries/:libraryId/groups", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "library_groups.update", "capabilityId": "LIB-29", "method": "PATCH", "route": "/v1/library-groups/:groupId", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "library_groups.delete", "capabilityId": "LIB-29", "method": "DELETE", "route": "/v1/library-groups/:groupId", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "library_entries.get", "capabilityId": "LIB-05", "method": "GET", "route": "/v1/library-entries/:entryId", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "libraries.entries.create", "capabilityId": "LIB-06", "method": "POST", "route": "/v1/libraries/:libraryId/entries", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "library_entries.delete", "capabilityId": "LIB-07", "method": "DELETE", "route": "/v1/library-entries/:entryId", "requiredScopes": ["libraries:write"], "assurance": "mfa_if_team_library_write", "classification": "delegated_action"},
  {"id": "library_entries.discover", "capabilityId": "LIB-08", "method": "POST", "route": "/v1/library-entries/:entryId/discoveries", "requiredScopes": ["libraries:write"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "library_entries.preview", "capabilityId": "LIB-09", "method": "POST", "route": "/v1/library-entries/:entryId/previews", "requiredScopes": ["libraries:write"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "library_entries.candidates.list", "capabilityId": "LIB-10", "method": "GET", "route": "/v1/library-entries/:entryId/candidates", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_candidates.get", "capabilityId": "LIB-10", "method": "GET", "route": "/v1/library-candidates/:candidateId", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_candidates.import", "capabilityId": "LIB-11", "method": "POST", "route": "/v1/library-candidates/:candidateId/import", "requiredScopes": ["libraries:write", "skills:submit"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "library_candidates.ignore", "capabilityId": "LIB-12", "method": "POST", "route": "/v1/library-candidates/:candidateId/ignore", "requiredScopes": ["libraries:write"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "library_candidates.self_review", "capabilityId": "LIB-13", "method": "POST", "route": "/v1/library-candidates/:candidateId/self-review", "requiredScopes": ["libraries:write", "skills:submit"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "library_candidates.request_instance_review", "capabilityId": "LIB-14", "method": "POST", "route": "/v1/library-candidates/:candidateId/instance-review-requests", "requiredScopes": ["libraries:write", "skills:submit"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "library_entries.adopt", "capabilityId": "LIB-15", "method": "POST", "route": "/v1/library-entries/:entryId/adoptions", "requiredScopes": ["libraries:write"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "library_entries.adoptions.list", "capabilityId": "LIB-16", "method": "GET", "route": "/v1/library-entries/:entryId/adoptions", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_entries.resolve", "capabilityId": "LIB-17", "method": "GET", "route": "/v1/library-entries/:entryId/resolution", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_entries.tracking.update", "capabilityId": "LIB-18", "method": "PATCH", "route": "/v1/library-entries/:entryId/tracking", "requiredScopes": ["libraries:write"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_entries.check", "capabilityId": "LIB-19", "method": "POST", "route": "/v1/library-entries/:entryId/checks", "requiredScopes": ["libraries:write"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "libraries.subscription.set", "capabilityId": "LIB-20", "method": "PUT", "route": "/v1/libraries/:libraryId/subscription", "requiredScopes": ["libraries:write"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "libraries.subscription.delete", "capabilityId": "LIB-20", "method": "DELETE", "route": "/v1/libraries/:libraryId/subscription", "requiredScopes": ["libraries:write"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "library_inbox.list", "capabilityId": "LIB-21", "method": "GET", "route": "/v1/library-inbox", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_inbox.mark_read", "capabilityId": "LIB-21", "method": "POST", "route": "/v1/library-inbox/read", "requiredScopes": ["libraries:write"], "assurance": "service_resource_policy", "classification": "delegated_action"},
  {"id": "library_entries.bindings.list", "capabilityId": "LIB-22", "method": "GET", "route": "/v1/library-entries/:entryId/bindings", "requiredScopes": ["libraries:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "library_entries.bindings.create", "capabilityId": "LIB-23", "method": "POST", "route": "/v1/library-entries/:entryId/bindings", "requiredScopes": ["libraries:bind", "targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "library_bindings.delete", "capabilityId": "LIB-23", "method": "DELETE", "route": "/v1/library-bindings/:bindingId", "requiredScopes": ["libraries:bind", "targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.libraries.settings.get", "capabilityId": "LIB-24", "method": "GET", "route": "/v1/admin/library-settings", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.libraries.settings.update", "capabilityId": "LIB-24", "method": "PUT", "route": "/v1/admin/library-settings", "requiredScopes": ["admin:settings"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "review.self_reviewed.list", "capabilityId": "LIB-25", "method": "GET", "route": "/v1/review/self-reviewed-releases", "requiredScopes": ["review:read"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "review.self_reviewed.export", "capabilityId": "LIB-25", "method": "GET", "route": "/v1/review/self-reviewed-releases/:submissionId/bundle", "requiredScopes": ["review:read"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "review.self_reviewed.elevate", "capabilityId": "LIB-25", "method": "POST", "route": "/v1/review/self-reviewed-releases/:submissionId/elevate", "requiredScopes": ["review:write"], "assurance": "mfa_if_privileged_role", "classification": "delegated_action"},
  {"id": "teams.list", "capabilityId": "TEAM-01", "method": "GET", "route": "/v1/teams", "requiredScopes": ["teams:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "teams.create", "capabilityId": "TEAM-02", "method": "POST", "route": "/v1/teams", "requiredScopes": ["teams:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "teams.invitations.create", "capabilityId": "TEAM-03", "method": "POST", "route": "/v1/teams/:id/invitations", "requiredScopes": ["teams:write"], "assurance": "mfa_if_team_owner", "classification": "delegated_action"},
  {"id": "teams.invitations.accept", "capabilityId": "TEAM-03", "method": "POST", "route": "/v1/teams/invitations/:id/accept", "requiredScopes": ["teams:write"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "teams.invitations.revoke", "capabilityId": "TEAM-04", "method": "DELETE", "route": "/v1/teams/:teamId/invitations/:invitationId", "requiredScopes": ["teams:write"], "assurance": "mfa_if_team_owner", "classification": "delegated_action"},
  {"id": "teams.members.update", "capabilityId": "TEAM-05", "method": "PUT", "route": "/v1/teams/:teamId/members/:memberId", "requiredScopes": ["teams:write"], "assurance": "mfa_if_team_owner", "classification": "delegated_action"},
  {"id": "teams.members.remove", "capabilityId": "TEAM-05", "method": "DELETE", "route": "/v1/teams/:teamId/members/:memberId", "requiredScopes": ["teams:write"], "assurance": "mfa_if_team_owner", "classification": "delegated_action"},
  {"id": "teams.shared_skills.list", "capabilityId": "TEAM-06", "method": "GET", "route": "/v1/teams/shared-skills", "requiredScopes": ["teams:read", "skills:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.list", "capabilityId": "ORG-01", "method": "GET", "route": "/v1/organizations", "requiredScopes": ["organizations:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.get", "capabilityId": "ORG-01", "method": "GET", "route": "/v1/organizations/:id", "requiredScopes": ["organizations:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.create", "capabilityId": "ORG-02", "method": "POST", "route": "/v1/organizations", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "organizations.lifecycle.decide", "capabilityId": "ORG-02", "method": "POST", "route": "/v1/organizations/:id/actions", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "organizations.members.list", "capabilityId": "ORG-03", "method": "GET", "route": "/v1/organizations/:id/members", "requiredScopes": ["organizations:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.invitations.list", "capabilityId": "ORG-03", "method": "GET", "route": "/v1/organizations/:id/invitations", "requiredScopes": ["organizations:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.my_invitations.list", "capabilityId": "ORG-03", "method": "GET", "route": "/v1/organizations/invitations", "requiredScopes": ["organizations:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.invitations.create", "capabilityId": "ORG-04", "method": "POST", "route": "/v1/organizations/:id/invitations", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "organizations.invitations.accept", "capabilityId": "ORG-04", "method": "POST", "route": "/v1/organizations/invitations/:id/accept", "requiredScopes": ["organizations:write"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.members.update", "capabilityId": "ORG-05", "method": "PUT", "route": "/v1/organizations/:id/members/:memberId", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "organizations.members.remove", "capabilityId": "ORG-05", "method": "DELETE", "route": "/v1/organizations/:id/members/:memberId", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "organizations.policies.list", "capabilityId": "ORG-06", "method": "GET", "route": "/v1/organizations/:id/policy-revisions", "requiredScopes": ["organizations:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.policies.append", "capabilityId": "ORG-06", "method": "POST", "route": "/v1/organizations/:id/policy-revisions", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "organizations.policies.decide", "capabilityId": "ORG-06", "method": "POST", "route": "/v1/organizations/:id/policy-revisions/:revisionId/actions", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "organizations.teams.list", "capabilityId": "ORG-07", "method": "GET", "route": "/v1/organizations/:id/teams", "requiredScopes": ["organizations:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.teams.create", "capabilityId": "ORG-07", "method": "POST", "route": "/v1/organizations/:id/teams", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "teams.organization.set", "capabilityId": "ORG-07", "method": "PUT", "route": "/v1/teams/:id/organization", "requiredScopes": ["teams:write", "organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "organizations.update_policy.get", "capabilityId": "ORG-08", "method": "GET", "route": "/v1/organizations/:id/update-policy", "requiredScopes": ["organizations:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "organizations.update_policy.set", "capabilityId": "ORG-08", "method": "PUT", "route": "/v1/organizations/:id/update-policy", "requiredScopes": ["organizations:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "architectures.patterns.list", "capabilityId": "ARC-01", "method": "GET", "route": "/v1/architecture-patterns", "requiredScopes": ["architectures:read"], "assurance": "public_metadata", "classification": "delegated_action"},
  {"id": "architectures.list", "capabilityId": "ARC-02", "method": "GET", "route": "/v1/architectures", "requiredScopes": ["architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architectures.get", "capabilityId": "ARC-03", "method": "GET", "route": "/v1/architectures/:id", "requiredScopes": ["architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architectures.revisions.list", "capabilityId": "ARC-03", "method": "GET", "route": "/v1/architectures/:id/revisions", "requiredScopes": ["architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architectures.revisions.get", "capabilityId": "ARC-03", "method": "GET", "route": "/v1/architectures/:id/revisions/:revisionId", "requiredScopes": ["architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architectures.create", "capabilityId": "ARC-04", "method": "POST", "route": "/v1/architectures", "requiredScopes": ["architectures:write"], "assurance": "mfa_if_privileged_role_or_team_architecture", "classification": "delegated_action"},
  {"id": "architectures.revisions.append", "capabilityId": "ARC-05", "method": "POST", "route": "/v1/architectures/:id/revisions", "requiredScopes": ["architectures:write"], "assurance": "mfa_if_privileged_role_or_team_architecture", "classification": "delegated_action"},
  {"id": "architectures.preview", "capabilityId": "ARC-06", "method": "POST", "route": "/v1/architectures/:id/preview", "requiredScopes": ["architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architectures.draft.preview", "capabilityId": "ARC-07", "method": "POST", "route": "/v1/architectures/:id/draft-preview", "requiredScopes": ["architectures:write"], "assurance": "mfa_if_privileged_role_or_team_architecture", "classification": "delegated_action"},
  {"id": "architectures.organization_grants.get", "capabilityId": "ARC-08", "method": "GET", "route": "/v1/architectures/:id/organization-grants", "requiredScopes": ["sharing:read", "architectures:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architectures.organization_grants.replace", "capabilityId": "ARC-08", "method": "PUT", "route": "/v1/architectures/:id/organization-grants", "requiredScopes": ["sharing:write", "architectures:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "architectures.pattern_migration.preview", "capabilityId": "ARC-09", "method": "POST", "route": "/v1/architectures/:id/pattern-migrations/preview", "requiredScopes": ["architectures:write"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "architectures.pattern_migration.create", "capabilityId": "ARC-09", "method": "POST", "route": "/v1/architectures/:id/pattern-migrations", "requiredScopes": ["architectures:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "targets.list", "capabilityId": "TGT-01", "method": "GET", "route": "/v1/architecture-targets", "requiredScopes": ["targets:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "targets.get", "capabilityId": "TGT-01", "method": "GET", "route": "/v1/architecture-targets/:id", "requiredScopes": ["targets:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "targets.register", "capabilityId": "TGT-02", "method": "POST", "route": "/v1/architecture-targets", "requiredScopes": ["targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "targets.consent.set", "capabilityId": "TGT-02", "method": "POST", "route": "/v1/architecture-targets/:id/consent", "requiredScopes": ["targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "targets.observations.list", "capabilityId": "TGT-03", "method": "GET", "route": "/v1/architecture-targets/:id/observations", "requiredScopes": ["targets:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "targets.revoke", "capabilityId": "TGT-06", "method": "DELETE", "route": "/v1/architecture-targets/:id", "requiredScopes": ["targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "targets.updates.list", "capabilityId": "TGT-07", "method": "GET", "route": "/v1/architecture-targets/:id/updates", "requiredScopes": ["targets:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "targets.operations.schedule", "capabilityId": "TGT-08", "method": "POST", "route": "/v1/architecture-targets/:id/operations", "requiredScopes": ["targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "target_operations.batch.schedule", "capabilityId": "TGT-09", "method": "POST", "route": "/v1/target-operations/batch", "requiredScopes": ["targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "targets.operations.list", "capabilityId": "TGT-10", "method": "GET", "route": "/v1/architecture-targets/:id/operations", "requiredScopes": ["targets:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "target_operations.get", "capabilityId": "TGT-10", "method": "GET", "route": "/v1/target-operations/:id", "requiredScopes": ["targets:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "target_operations.cancel", "capabilityId": "TGT-11", "method": "POST", "route": "/v1/target-operations/:id/cancel", "requiredScopes": ["targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "targets.update_policy.get", "capabilityId": "TGT-12", "method": "GET", "route": "/v1/architecture-targets/:id/update-policy", "requiredScopes": ["targets:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "targets.update_policy.set", "capabilityId": "TGT-12", "method": "PUT", "route": "/v1/architecture-targets/:id/update-policy", "requiredScopes": ["targets:control"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "improvements.compatibility.get", "capabilityId": "IMP-01", "method": "GET", "route": "/v1/improvements/releases/:slug/:version/compatibility", "requiredScopes": ["improvements:read"], "assurance": "authenticated_or_existing_public_read", "classification": "delegated_action"},
  {"id": "improvements.declarations.append", "capabilityId": "IMP-02", "method": "POST", "route": "/v1/improvements/releases/:slug/:version/declarations", "requiredScopes": ["skills:submit"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.declarations.review", "capabilityId": "IMP-02", "method": "POST", "route": "/v1/improvements/releases/:slug/:version/declarations/:revisionId/review", "requiredScopes": ["review:write"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "improvements.policy.get", "capabilityId": "IMP-03", "method": "GET", "route": "/v1/improvements/policies/:scopeType/:scopeId", "requiredScopes": ["improvements:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.policy.set", "capabilityId": "IMP-03", "method": "PUT", "route": "/v1/improvements/policies/:scopeType/:scopeId", "requiredScopes": ["improvements:configure"], "assurance": "mfa_if_nonpersonal_improvement_scope", "classification": "delegated_action"},
  {"id": "improvements.profiles.list", "capabilityId": "IMP-04", "method": "GET", "route": "/v1/improvements/profiles", "requiredScopes": ["improvements:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.profiles.create", "capabilityId": "IMP-04", "method": "POST", "route": "/v1/improvements/profiles", "requiredScopes": ["improvements:configure"], "assurance": "mfa_if_nonpersonal_improvement_scope", "classification": "delegated_action"},
  {"id": "improvements.profiles.get", "capabilityId": "IMP-04", "method": "GET", "route": "/v1/improvements/profiles/:id", "requiredScopes": ["improvements:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.profiles.append", "capabilityId": "IMP-04", "method": "PUT", "route": "/v1/improvements/profiles/:id", "requiredScopes": ["improvements:configure"], "assurance": "mfa_if_nonpersonal_improvement_scope", "classification": "delegated_action"},
  {"id": "improvements.suites.list", "capabilityId": "IMP-05", "method": "GET", "route": "/v1/improvements/suites", "requiredScopes": ["improvements:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.suites.create", "capabilityId": "IMP-05", "method": "POST", "route": "/v1/improvements/suites", "requiredScopes": ["improvements:configure"], "assurance": "mfa_if_nonpersonal_improvement_scope", "classification": "delegated_action"},
  {"id": "improvements.suites.get", "capabilityId": "IMP-05", "method": "GET", "route": "/v1/improvements/suites/:id", "requiredScopes": ["improvements:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.suites.append", "capabilityId": "IMP-05", "method": "PUT", "route": "/v1/improvements/suites/:id", "requiredScopes": ["improvements:configure"], "assurance": "mfa_if_nonpersonal_improvement_scope", "classification": "delegated_action"},
  {"id": "improvements.plans.preview", "capabilityId": "IMP-06", "method": "POST", "route": "/v1/improvements/plans/preview", "requiredScopes": ["improvements:run"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.plans.create", "capabilityId": "IMP-06", "method": "POST", "route": "/v1/improvements/plans", "requiredScopes": ["improvements:run"], "assurance": "mfa_if_nonpersonal_improvement_scope", "classification": "delegated_action"},
  {"id": "improvements.plans.get", "capabilityId": "IMP-06", "method": "GET", "route": "/v1/improvements/plans/:id", "requiredScopes": ["improvements:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.runs.get", "capabilityId": "IMP-08", "method": "GET", "route": "/v1/improvements/runs/:id", "requiredScopes": ["improvements:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.runs.cancel", "capabilityId": "IMP-08", "method": "POST", "route": "/v1/improvements/runs/:id/cancel", "requiredScopes": ["improvements:run"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.evidence.share", "capabilityId": "IMP-09", "method": "POST", "route": "/v1/improvements/runs/:id/evidence", "requiredScopes": ["improvements:report"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.evidence.get", "capabilityId": "IMP-10", "method": "GET", "route": "/v1/improvements/evidence/:id", "requiredScopes": ["improvements:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "improvements.evidence.decide", "capabilityId": "IMP-10", "method": "POST", "route": "/v1/improvements/evidence/:id/acceptances", "requiredScopes": ["improvements:report"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "account.identity.get", "capabilityId": "ACC-03", "method": "GET", "route": "/v1/me", "requiredScopes": ["profile:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "account.mfa.status", "capabilityId": "ACC-07", "method": "GET", "route": "/v1/auth/mfa", "requiredScopes": ["account:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "account.tokens.list", "capabilityId": "ACC-08", "method": "GET", "route": "/v1/auth/api-tokens", "requiredScopes": ["account:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "account.tokens.revoke", "capabilityId": "ACC-08", "method": "DELETE", "route": "/v1/auth/api-tokens/:id", "requiredScopes": ["account:tokens:revoke"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "connections.connector.get", "capabilityId": "ACC-09", "method": "GET", "route": "/v1/oauth/connector", "requiredScopes": [], "assurance": "public_metadata", "classification": "public_metadata"},
  {"id": "connections.list", "capabilityId": "ACC-09", "method": "GET", "route": "/v1/oauth/connections", "requiredScopes": ["account:read"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "connections.revoke", "capabilityId": "ACC-09", "method": "DELETE", "route": "/v1/oauth/connections/:id", "requiredScopes": ["account:connections:revoke"], "assurance": "authenticated", "classification": "delegated_action"},
  {"id": "instance.branding.get", "capabilityId": "ADM-01", "method": "GET", "route": "/v1/branding", "requiredScopes": [], "assurance": "public_metadata", "classification": "public_metadata"},
  {"id": "instance.site.get", "capabilityId": "ADM-01", "method": "GET", "route": "/v1/site", "requiredScopes": [], "assurance": "public_metadata", "classification": "public_metadata"},
  {"id": "admin.branding.get", "capabilityId": "ADM-02", "method": "GET", "route": "/v1/admin/branding", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.branding.update", "capabilityId": "ADM-02", "method": "PUT", "route": "/v1/admin/branding", "requiredScopes": ["admin:settings"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.site.get", "capabilityId": "ADM-03", "method": "GET", "route": "/v1/admin/site", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.site.update", "capabilityId": "ADM-03", "method": "PUT", "route": "/v1/admin/site", "requiredScopes": ["admin:settings"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.registration.get", "capabilityId": "ADM-04", "method": "GET", "route": "/v1/admin/registration", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.registration.set", "capabilityId": "ADM-04", "method": "PUT", "route": "/v1/admin/registration", "requiredScopes": ["admin:settings"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.registration.invite", "capabilityId": "ADM-04", "method": "POST", "route": "/v1/admin/registration/invitations", "requiredScopes": ["admin:users"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.sharing.get", "capabilityId": "ADM-05", "method": "GET", "route": "/v1/admin/sharing", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.sharing.set", "capabilityId": "ADM-05", "method": "PUT", "route": "/v1/admin/sharing", "requiredScopes": ["admin:settings"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.providers.list", "capabilityId": "ADM-06", "method": "GET", "route": "/v1/admin/providers", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.providers.upsert", "capabilityId": "ADM-06", "method": "PUT", "route": "/v1/admin/providers/:key", "requiredScopes": ["admin:settings"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.users.list", "capabilityId": "ADM-07", "method": "GET", "route": "/v1/admin/users", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.users.lifecycle.decide", "capabilityId": "ADM-07", "method": "POST", "route": "/v1/admin/users/:id/actions", "requiredScopes": ["admin:users"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.users.roles.set", "capabilityId": "ADM-08", "method": "PUT", "route": "/v1/admin/users/:id/roles", "requiredScopes": ["admin:users"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.tokens.list", "capabilityId": "ADM-09", "method": "GET", "route": "/v1/admin/api-tokens", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.tokens.revoke", "capabilityId": "ADM-09", "method": "DELETE", "route": "/v1/admin/api-tokens/:id", "requiredScopes": ["admin:tokens:revoke"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "admin.audit.list", "capabilityId": "ADM-10", "method": "GET", "route": "/v1/admin/audit", "requiredScopes": ["admin:read"], "assurance": "mfa", "classification": "delegated_action"},
  {"id": "system.health.get", "capabilityId": "SYS-01", "method": "GET", "route": "/health", "requiredScopes": [], "assurance": "public_metadata", "classification": "public_metadata"},
  {"id": "system.readiness.get", "capabilityId": "SYS-01", "method": "GET", "route": "/ready", "requiredScopes": [], "assurance": "public_metadata", "classification": "public_metadata"},
  {"id": "system.version.get", "capabilityId": "SYS-01", "method": "GET", "route": "/version.json", "requiredScopes": [], "assurance": "public_metadata", "classification": "public_metadata"},
  {"id": "system.features.get", "capabilityId": "SYS-01", "method": "GET", "route": "/v1/capabilities", "requiredScopes": [], "assurance": "public_metadata", "classification": "public_metadata"},
] as const satisfies readonly DelegatedAction[];

const actionsByRoute: ReadonlyMap<string, DelegatedAction> = new Map(DELEGATED_ACTIONS.map((action) => [`${action.method} ${action.route}`, action]));

/** Match registered route templates, never arbitrary URLs supplied by a caller. */
export function findDelegatedAction(method: string, registeredRoute: string): DelegatedAction | undefined {
  return actionsByRoute.get(`${method} ${registeredRoute}`);
}
