import { expect, test } from "@playwright/test";

/** Real browser + API + Postgres journey. No intercepted API responses. */
test("registry bundles keep relationships through inspect, save and Library reopen", async ({ page, request, baseURL }, testInfo) => {
  const browserErrors: string[] = [];
  page.on("pageerror", error => browserErrors.push(error.message));
  const token = process.env.MYSKILLS_ACCEPTANCE_OWNER_TOKEN;
  test.skip(!token, "A verified disposable full-stack owner session is required.");
  const headers = { authorization: `Bearer ${token}` };
  const me = await request.get("/api/v1/me", { headers });
  expect(me.ok()).toBeTruthy();
  const { user } = await me.json();
  const skillsResponse = await request.get("/api/v1/skills?limit=100", { headers });
  expect(skillsResponse.ok()).toBeTruthy();
  const { skills } = await skillsResponse.json();
  const skill = skills.find((row: {visibility:string}) => row.visibility === "public");
  expect(skill).toBeTruthy();
  const suffix = `${Date.now()}-${testInfo.workerIndex}`;
  const name = `Bundle journey ${suffix}`;
  const input = { kind: "curated", name, purpose: "A reviewed collection for the browser journey", owner: { type: "user" }, visibility: "public", memberSlugs: [skill.slug] };
  const created = await request.post("/api/v1/bundles", { headers, data: input });
  expect(created.status()).toBe(201);
  const { bundle } = await created.json();
  const overlap = await request.post("/api/v1/bundles", { headers, data: {...input,name:`Related ${suffix}`} });
  expect(overlap.status()).toBe(201);
  const libraryName = `Bundle references ${suffix}`;
  const libraryResponse = await request.post("/api/v1/libraries", {headers,data:{name:libraryName,owner:{type:"user"},clientMutationId:crypto.randomUUID()}});
  expect(libraryResponse.status()).toBe(201);
  const {library} = await libraryResponse.json();
  await page.context().addCookies([{name:"myskills_session",value:token!,url:baseURL!,httpOnly:true,sameSite:"Lax"}]);
  await page.addInitScript(({user})=>localStorage.setItem("myskills-app:web-session",JSON.stringify({user,expiresAt:new Date(Date.now()+3600000).toISOString()})),{user});
  await page.goto(`/registry?q=${encodeURIComponent(name)}`);
  await expect(page.getByRole("heading",{name:"Skill registry",exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:`Details for ${name}`,exact:true})).toBeVisible();
  await page.getByRole("button",{name:`Details for ${name}`,exact:true}).click();
  await expect(page.getByRole("heading",{name,exact:true,level:2})).toBeVisible();
  await page.getByRole("button",{name:"Save bundle to library",exact:true}).click();
  await page.getByRole("radio",{name:new RegExp(libraryName)}).check();
  const saveResponse=page.waitForResponse(r=>r.url().includes(`/bundles/${bundle.id}/library-references`)&&r.request().method()==="POST");
  await page.getByRole("button",{name:"Save reference",exact:true}).click();
  expect((await saveResponse).status()).toBe(201);
  const entriesResponse=await request.get(`/api/v1/libraries/${library.id}/entries`,{headers});
  const {entries}=await entriesResponse.json();
  expect(entries).toHaveLength(1);expect(entries[0]).toMatchObject({kind:"bundle",adoption:null,bundle:{id:bundle.id,revisionSaved:1,state:"available"}});
  const memberships=await request.get(`/api/v1/skills/${skill.slug}/bundles`,{headers});
  expect((await memberships.json()).bundles.map((b:{id:string})=>b.id)).toContain(bundle.id);
  await page.goto("/libraries");
  await expect(page.getByRole("heading",{name:"Libraries",exact:true})).toBeVisible();
  const libraryButton = page.getByRole("button", { name: libraryName, exact: true });
  const libraryHeading = page.getByRole("heading", { name: libraryName, exact: true });
  await expect(libraryButton.or(libraryHeading).first()).toBeVisible();
  if (await libraryButton.isVisible()) await libraryButton.click();
  await expect(libraryHeading).toBeVisible();
  await expect(page.getByRole("heading", { name, exact: true, level: 3 })).toBeVisible();
  await expect(page.getByRole("link",{name:"Open in registry",exact:true})).toBeVisible();
  await page.getByRole("link",{name:"Open in registry",exact:true}).click();
  await expect(page.getByRole("heading",{name,exact:true,level:2})).toBeVisible();
  expect(browserErrors).toEqual([]);
  await page.screenshot({path:testInfo.outputPath("bundle-fullstack.png"),fullPage:true});
  await testInfo.attach("bundle-persistence",{body:JSON.stringify({bundleId:bundle.id,entryId:entries[0].id,kind:entries[0].kind,adoption:entries[0].adoption}),contentType:"application/json"});
});
